# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1517987896);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1517988016);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1519125815);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1517987776);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1517987656);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160216145630");
user_pref("browser.slowStartup.averageTime", 22543);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20160216145630");
user_pref("browser.startup.homepage_override.mstone", "38.6.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1519125784285");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1519125798538");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1519212198538");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1516894675046");
user_pref("datareporting.policy.firstRunTime", "1516894611415");
user_pref("datareporting.sessions.current.activeTicks", 8);
user_pref("datareporting.sessions.current.firstPaint", 32219);
user_pref("datareporting.sessions.current.main", 8464);
user_pref("datareporting.sessions.current.sessionRestored", 43127);
user_pref("datareporting.sessions.current.startTime", "1519125680640");
user_pref("datareporting.sessions.current.totalTime", 92);
user_pref("datareporting.sessions.currentIndex", 21);
user_pref("datareporting.sessions.prunedIndex", 20);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 6);
user_pref("extensions.blocklist.pingCountVersion", 6);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.6.1");
user_pref("extensions.getAddons.cache.lastUpdate", 1517987897);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "38.6.1");
user_pref("extensions.lastPlatformVersion", "38.6.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.6.1\",\"st\":1516819608000,\"mt\":1455635247000}}}");
user_pref("gecko.buildID", "20160216145630");
user_pref("gecko.mstone", "38.6.1");
user_pref("idle.lastDailyNotification", 1519125829);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1516894688);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160216145630");
user_pref("media.gmp-manager.lastCheck", 1519125777);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1519125791);
user_pref("places.history.expiration.transient_current_max_pages", 29514);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1516896038);
user_pref("toolkit.startup.last_success", 1519125689);
user_pref("toolkit.telemetry.previousBuildID", "20160216145630");
